"tuning_type": "VeraFT"
"model_name": "deepfake_detection"
"real_folder": ['Real_5_k_split']
"fake_folder": ['StableDiffusion_split', 'StyleGAN2_split', 'Midjourney_split', 'firefly_split', 'Dall-E_split']
"num_epochs": 10
"batch_size": 16
"learning_rate": 0.0005
"use_wandb": True
"experiment_order": ["StyleGAN2_split", "Dall-E_split", "firefly_split", "Midjourney_split", "StableDiffusion_split"]
"experiment_name": "experiment1"
"test_split": [Test]

# Vera
"r": 8
"target_modules": ["self_attn.q_proj", "self_attn.v_proj"]
"vera_dropout": 0.05
"bias": "none"