"tuning_type": "FrozenFT"
"model_name": "deepfake_detection"
"real_folder": ['Real_1k_split']
"fake_folder": ['Dall-E_split'] #['StableDiffusion_split', 'StyleGAN2_split', 'Midjourney_split', 'firefly_split', 'Dall-E_split']
"num_epochs": 1 # doesn't matter
"batch_size": 10
"learning_rate": None
"use_wandb": False
"experiment_order": ["StyleGAN2_split", "Dall-E_split", "firefly_split", "Midjourney_split", "StableDiffusion_split"]
"experiment_name": "experiment1"
"test_split": [Test]