"tuning_type": "FullFT"
"model_name": "deepfake_detection"
"real_folder": ['Real_5_k_split']
"fake_folder": ['StableDiffusion_split', 'StyleGAN2_split', 'Midjourney_split', 'firefly_split', 'Dall-E_split']
"num_epochs": 15
"batch_size": 16
"learning_rate": 0.0005
"use_wandb": True
"experiment_order": ["StyleGAN2_split", "Dall-E_split", "firefly_split", "Midjourney_split", "StableDiffusion_split"]
"experiment_name": "experiment1"
"test_split": [Test]
