"tuning_type": "FullFT"
"model_name": "efficientnetv2_rw_m.agc_in1k"
"real_folder": "Real_split"
"fake_folder": "All_fakes_split"
"num_epochs": 20
"batch_size": 16
"learning_rate": 0.0005
"use_wandb": True
"experiment_order": ["StyleGAN2_split", "Dall-E_split", "firefly_split", "Midjourney_split", "StableDiffusion_split"]
"experiment_name": "experiment1"
"test_split": [Test]